### ISSUE TITLE
Missing dependency?

### ISSUE THREAD

**Issue by larsks** [noamraph/dreampie#46]
Running:

```
pip install dreampie
```

seems to work, but then running `dreampie` results in:

```
Traceback (most recent call last):
  File "/home/lkellogg/env/common/bin/dreampie", line 3, in <module>
    from dreampielib.gui import main
  File "/home/lkellogg/env/common/lib/python2.7/site-packages/dreampielib/gui/__init__.py", line 78, in <module>
    import gtksourceview2
ImportError: No module named gtksourceview2
```

Maybe there is a dependency missing from setup.py?  I have not investigated yet.

**Comment by mervick** [comment]
For Ubuntu execute in terminal:
```sh
sudo apt-get install python-gtksourceview2
```
