### ISSUE TITLE
Not running on debian stretch

### ISSUE THREAD

**Issue by ketsa** [noamraph/dreampie#75]
09:42-root@DL4310[/home/matt]>dreampie
Traceback (most recent call last):
  File "/usr/local/bin/dreampie", line 3, in <module>
    from dreampielib.gui import main
  File "/usr/local/lib/python3.5/dist-packages/dreampielib/gui/__init__.py", line 240
    except StartError, e:
                     ^
SyntaxError: invalid syntax

**Comment by bbayles** [comment]
Try using Python 2.7 instead - that works on Stretch.
