### ISSUE TITLE
Dreampie fails to start on Ubuntu Budgie 20.10

### ISSUE THREAD

**Issue by charwhee** [noamraph/dreampie#78]
dreampie

Traceback (most recent call last):
  File "/usr/local/bin/dreampie", line 3, in <module>
    from dreampielib.gui import main
  File "/usr/local/lib/python3.8/dist-packages/dreampielib/gui/__init__.py", line 240
    except StartError, e:
                     ^
SyntaxError: invalid syntax

**Comment by furas** [comment]
`dreampie` was created in `Python 2.7` and it needs  `Python 2.7`  to run it.  
You have to install in with `pip2 install ...` or `python2 -m pip installl ...`

If you don't have `Python 2.7` then you can install it from 
`deadsnakes` unofficial Python repo for Ubuntu (and Mint)

https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa

After that you can use `Python 3` inside `dreampie`

     $ dreampie python3
     $ dreampie python3.7
     $ dreampie python3.8

or even `ipython` or `bpython` installed in `Python 3`

     $ dreampie ipython
     $ dreampie bpython

---

`dreampie` was created in `Python 2.7` and as I know
It could need too much change to simply convert it to `Python 3` 
ie. it uses `gtksourceview2` which doesn't exists in `Python 3`
and I had problem to install it on `Linux Mint 20` based on `Ubuntu 20.04`

If you will have problem with `gtksourceview2` in `Python 2.7`
then  download `python-gtksourceview2_2.10.1-3_amd64.deb`
from 

https://ubuntu.pkgs.org/18.04/ubuntu-universe-amd64/python-gtksourceview2_2.10.1-3_amd64.deb.html

and install it with `double click` 

or uncompress it  using function built-in in Nautilus/Caja
or using `dpkg -x python-gtksourceview2_2.10.1-3_amd64.deb folder`

and copy `gtksourceview2.so` to folder with `Python 2` 

At Linux Mint it is `/usr/lib/python2.7/dist-packages/gtksourceview2.so`
